//
//  ViewController.swift
//  Example
//
//  Created by Anand Kore on 12/10/18.
//  Copyright © 2018 Anand Kore. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
    }


}

extension String{
    
    func localizableString(loc:LanguageCode) -> String{
        if let path = Bundle.main.path(forResource:loc.rawValue, ofType:"lproj") //lproj is localizations file extension.
        {
            if let bundle = Bundle(path:path){
                return NSLocalizedString(self, tableName:nil, bundle:bundle, value:"", comment: "")
            }
        }
        return self
    }
}

enum LanguageCode:String{
    case Afrikaans = "af"
    case Afrikaans_South_Africa = "af-ZA"
    case Arabic = "ar"
    case Arabic_U_A_E_ = "ar-AE"
    case Arabic_Bahrain = "ar-BH"
    case Arabic_Algeria = "ar-DZ"
    case Arabic_Egypt = "ar-EG"
    case Arabic_Iraq = "ar-IQ"
    case Arabic_Jordan = "ar-JO"
    case Arabic_Kuwait = "ar-KW"
    case Arabic_Lebanon = "ar-LB"
    case Arabic_Libya = "ar-LY"
    case Arabic_Morocco = "ar-MA"
    case Arabic_Oman = "ar-OM"
    case Arabic_Qatar = "ar-QA"
    case Arabic_Saudi_Arabia = "ar-SA"
    case Arabic_Syria = "ar-SY"
    case Arabic_Tunisia = "ar-TN"
    case Arabic_Yemen = "ar-YE"
    case Azeri_Latin = "az"
    case Azeri_Cyrillic_Latin_Azerbaijan = "az-AZ"
    case Belarusian = "be"
    case Belarusian_Belarus = "be-BY"
    case Bulgarian = "bg"
    case Bulgarian_Bulgaria = "bg-BG"
    case Bosnian_Bosnia_and_Herzegovina = "bs-BA"
    case Catalan = "ca"
    case Catalan_Spain = "ca-ES"
    case Czech = "cs"
    case Czech_Czech_Republic = "cs-CZ"
    case Welsh = "cy"
    case Welsh_United_Kingdom = "cy-GB"
    case Danish = "da"
    case Danish_Denmark = "da-DK"
    case German = "de"
    case German_Austria = "de-AT"
    case German_Switzerland = "de-CH"
    case German_Germany = "de-DE"
    case German_Liechtenstein = "de-LI"
    case German_Luxembourg = "de-LU"
    case Divehi = "dv"
    case Divehi_Maldives = "dv-MV"
    case Greek = "el"
    case Greek_Greece = "el-GR"
    case English = "en"
    case English_Australia = "en-AU"
    case English_Belize = "en-BZ"
    case English_Canada = "en-CA"
    case English_Caribbean = "en-CB"
    case English_United_Kingdom = "en-GB"
    case English_Ireland = "en-IE"
    case English_Jamaica = "en-JM"
    case English_New_Zealand = "en-NZ"
    case English_Republic_of_the_Philippines = "en-PH"
    case English_Trinidad_and_Tobago = "en-TT"
    case English_United_States = "en-US"
    case English_South_Africa = "en-ZA"
    case English_Zimbabwe = "en-ZW"
    case Esperanto = "eo"
    case Spanish = "es"
    case Spanish_Argentina = "es-AR"
    case Spanish_Bolivia = "es-BO"
    case Spanish_Chile = "es-CL"
    case Spanish_Colombia = "es-CO"
    case Spanish_Costa_Rica = "es-CR"
    case Spanish_Dominican_Republic = "es-DO"
    case Spanish_Ecuador = "es-EC"
    case Spanish_Castilian_Spain = "es-ES"
    case Spanish_Guatemala = "es-GT"
    case Spanish_Honduras = "es-HN"
    case Spanish_Mexico = "es-MX"
    case Spanish_Nicaragua = "es-NI"
    case Spanish_Panama = "es-PA"
    case Spanish_Peru = "es-PE"
    case Spanish_Puerto_Rico = "es-PR"
    case Spanish_Paraguay = "es-PY"
    case Spanish_El_Salvador = "es-SV"
    case Spanish_Uruguay = "es-UY"
    case Spanish_Venezuela = "es-VE"
    case Estonian = "et"
    case Estonian_Estonia = "et-EE"
    case Basque = "eu"
    case Basque_Spain = "eu-ES"
    case Farsi = "fa"
    case Farsi_Iran = "fa-IR"
    case Finnish = "fi"
    case Finnish_Finland = "fi-FI"
    case Faroese = "fo"
    case Faroese_Faroe_Islands = "fo-FO"
    case French = "fr"
    case French_Belgium = "fr-BE"
    case French_Canada = "fr-CA"
    case French_Switzerland = "fr-CH"
    case French_France = "fr-FR"
    case French_Luxembourg = "fr-LU"
    case French_Principality_of_Monaco = "fr-MC"
    case Galician = "gl"
    case Galician_Spain = "gl-ES"
    case Gujarati = "gu"
    case Gujarati_India = "gu-IN"
    case Hebrew = "he"
    case Hebrew_Israel = "he-IL"
    case Hindi = "hi"
    case Hindi_India = "hi-IN"
    case Croatian = "hr"
    case Croatian_Bosnia_and_Herzegovina = "hr-BA"
    case Croatian_Croatia = "hr-HR"
    case Hungarian = "hu"
    case Hungarian_Hungary = "hu-HU"
    case Armenian = "hy"
    case Armenian_Armenia = "hy-AM"
    case Indonesian = "id"
    case Indonesian_Indonesia = "id-ID"
    case Icelandic = "is"
    case Icelandic_Iceland = "is-IS"
    case Italian = "it"
    case Italian_Switzerland = "it-CH"
    case Italian_Italy = "it-IT"
    case Japanese = "ja"
    case Japanese_Japan = "ja-JP"
    case Georgian = "ka"
    case Georgian_Georgia = "ka-GE"
    case Kazakh = "kk"
    case Kazakh_Kazakhstan = "kk-KZ"
    case Kannada = "kn"
    case Kannada_India = "kn-IN"
    case Korean = "ko"
    case Korean_Korea = "ko-KR"
    case Konkani = "kok"
    case Konkani_India = "kok-IN"
    case Kyrgyz = "ky"
    case Kyrgyz_Kyrgyzstan = "ky-KG"
    case Lithuanian = "lt"
    case Lithuanian_Lithuania = "lt-LT"
    case Latvian = "lv"
    case Latvian_Latvia = "lv-LV"
    case Maori = "mi"
    case Maori_New_Zealand = "mi-NZ"
    case FYRO_Macedonian = "mk"
    case FYRO_Macedonian_Former_Yugoslav_Republic_of_Macedonia = "mk-MK"
    case Mongolian = "mn"
    case Mongolian_Mongolia = "mn-MN"
    case Marathi = "mr"
    case Marathi_India = "mr-IN"
    case Malay = "ms"
    case Malay_Brunei_Darussalam = "ms-BN"
    case Malay_Malaysia = "ms-MY"
    case Maltese = "mt"
    case Maltese_Malta = "mt-MT"
    case Norwegian_Bokml = "nb"
    case Norwegian_Bokml_Norway = "nb-NO"
    case Dutch = "nl"
    case Dutch_Belgium = "nl-BE"
    case Dutch_Netherlands = "nl-NL"
    case Norwegian_Nynorsk_Norway = "nn-NO"
    case Northern_Sotho = "ns"
    case Northern_Sotho_South_Africa = "ns-ZA"
    case Punjabi = "pa"
    case Punjabi_India = "pa-IN"
    case Polish = "pl"
    case Polish_Poland = "pl-PL"
    case Pashto = "ps"
    case Pashto_Afghanistan = "ps-AR"
    case Portuguese = "pt"
    case Portuguese_Brazil = "pt-BR"
    case Portuguese_Portugal = "pt-PT"
    case Quechua = "qu"
    case Quechua_Bolivia = "qu-BO"
    case Quechua_Ecuador = "qu-EC"
    case Quechua_Peru = "qu-PE"
    case Romanian = "ro"
    case Romanian_Romania = "ro-RO"
    case Russian = "ru"
    case Russian_Russia = "ru-RU"
    case Sanskrit = "sa"
    case Sanskrit_India = "sa-IN"
    case Sami_Northern = "se"
    case Sami_Inari_Skolt_Northern_Finland = "se-FI"
    case Sami_Southern_Lule_Northern_Norway = "se-NO"
    case Sami_Lule_Southern_Northern_Sweden = "se-SE"
    case Slovak = "sk"
    case Slovak_Slovakia = "sk-SK"
    case Slovenian = "sl"
    case Slovenian_Slovenia = "sl-SI"
    case Albanian = "sq"
    case Albanian_Albania = "sq-AL"
    case Serbian_Cyrillic_Latin_Bosnia_and_Herzegovina = "sr-BA"
    case Serbian_Cyrillic_Latin_Serbia_and_Montenegro = "sr-SP"
    case Swedish = "sv"
    case Swedish_Finland = "sv-FI"
    case Swedish_Sweden = "sv-SE"
    case Swahili = "sw"
    case Swahili_Kenya = "sw-KE"
    case Syriac = "syr"
    case Syriac_Syria = "syr-SY"
    case Tamil = "ta"
    case Tamil_India = "ta-IN"
    case Telugu = "te"
    case Telugu_India = "te-IN"
    case Thai = "th"
    case Thai_Thailand = "th-TH"
    case Tagalog = "tl"
    case Tagalog_Philippines = "tl-PH"
    case Tswana = "tn"
    case Tswana_South_Africa = "tn-ZA"
    case Turkish = "tr"
    case Turkish_Turkey = "tr-TR"
    case Tatar = "tt"
    case Tatar_Russia = "tt-RU"
    case Tsonga = "ts"
    case Ukrainian = "uk"
    case Ukrainian_Ukraine = "uk-UA"
    case Urdu = "ur"
    case Urdu_Islamic_Republic_of_Pakistan = "ur-PK"
    case Uzbek_Latin = "uz"
    case Uzbek_Cyrillic_Latin_Uzbekistan = "uz-UZ"
    case Vietnamese = "vi"
    case Vietnamese_Viet_Nam = "vi-VN"
    case Xhosa = "xh"
    case Xhosa_South_Africa = "xh-ZA"
    case Chinese = "zh"
    case Chinese_S = "zh-CN"
    case Chinese_Hong_Kong = "zh-HK"
    case Chinese_Macau = "zh-MO"
    case Chinese_Singapore = "zh-SG"
    case Chinese_T = "zh-TW"
    case Zulu = "zu"
    case Zulu_South_Africa = "zu-ZA"
}
